import { CS2Config } from '../types/config';
import { DEFAULT_CONFIG } from './cs2Settings';

export const PRO_PRESETS: CS2Config[] = [
  {
    ...DEFAULT_CONFIG,
    id: 'preset-s1mple',
    name: 's1mple',
    isPreset: true,
    author: 's1mple (Natus Vincere)',
    gameplay: {
      ...DEFAULT_CONFIG.gameplay,
      sensitivity: '2.5',
      zoomSensitivity: 1.0,
    },
    crosshair: {
      ...DEFAULT_CONFIG.crosshair,
      style: 4,
      size: 2.5,
      thickness: 0,
      gap: -2,
      outline: 1,
      colorR: 50,
      colorG: 250,
      colorB: 50,
      dot: 1,
      dotSize: 1,
    },
    viewmodel: {
      ...DEFAULT_CONFIG.viewmodel,
      fov: 68,
      offsetX: 2.5,
      offsetY: 0,
      offsetZ: -1.5,
    },
  },
  {
    ...DEFAULT_CONFIG,
    id: 'preset-zywoo',
    name: 'ZywOo',
    isPreset: true,
    author: 'ZywOo (Vitality)',
    gameplay: {
      ...DEFAULT_CONFIG.gameplay,
      sensitivity: '1.6',
      zoomSensitivity: 1.0,
    },
    crosshair: {
      ...DEFAULT_CONFIG.crosshair,
      style: 4,
      size: 2,
      thickness: 0,
      gap: -2,
      outline: 1,
      colorR: 50,
      colorG: 50,
      colorB: 250,
      dot: 1,
      dotSize: 1,
    },
    viewmodel: {
      ...DEFAULT_CONFIG.viewmodel,
      fov: 60,
      offsetX: 1,
      offsetY: 1,
      offsetZ: -1,
    },
  },
  {
    ...DEFAULT_CONFIG,
    id: 'preset-niko',
    name: 'NiKo',
    isPreset: true,
    author: 'NiKo (G2 Esports)',
    gameplay: {
      ...DEFAULT_CONFIG.gameplay,
      sensitivity: '1.3',
      zoomSensitivity: 1.0,
    },
    crosshair: {
      ...DEFAULT_CONFIG.crosshair,
      style: 4,
      size: 2.5,
      thickness: 0,
      gap: -3,
      outline: 0,
      colorR: 250,
      colorG: 250,
      colorB: 250,
      dot: 1,
      dotSize: 1,
    },
    viewmodel: {
      ...DEFAULT_CONFIG.viewmodel,
      fov: 68,
      offsetX: 2.5,
      offsetY: 0,
      offsetZ: -1.5,
    },
  },
  {
    ...DEFAULT_CONFIG,
    id: 'preset-device',
    name: 'device',
    isPreset: true,
    author: 'device (Astralis)',
    gameplay: {
      ...DEFAULT_CONFIG.gameplay,
      sensitivity: '1.7',
      zoomSensitivity: 1.0,
    },
    crosshair: {
      ...DEFAULT_CONFIG.crosshair,
      style: 4,
      size: 2,
      thickness: 0,
      gap: -2,
      outline: 1,
      colorR: 50,
      colorG: 250,
      colorB: 50,
      dot: 0,
      dotSize: 0,
    },
    viewmodel: {
      ...DEFAULT_CONFIG.viewmodel,
      fov: 68,
      offsetX: 2.5,
      offsetY: 0,
      offsetZ: -1.5,
    },
  },
  {
    ...DEFAULT_CONFIG,
    id: 'preset-ropz',
    name: 'ropz',
    isPreset: true,
    author: 'ropz (FaZe Clan)',
    gameplay: {
      ...DEFAULT_CONFIG.gameplay,
      sensitivity: '1.7',
      zoomSensitivity: 1.0,
    },
    crosshair: {
      ...DEFAULT_CONFIG.crosshair,
      style: 4,
      size: 2.5,
      thickness: 0,
      gap: -2,
      outline: 1,
      colorR: 50,
      colorG: 250,
      colorB: 50,
      dot: 1,
      dotSize: 1,
    },
    viewmodel: {
      ...DEFAULT_CONFIG.viewmodel,
      fov: 68,
      offsetX: 2.5,
      offsetY: 0,
      offsetZ: -1.5,
    },
  },
];
